version: '3.4'
services:
  datalustseq:
    image: datalust/seq:latest
    container_name: datalust-seq
    environment:
     - ACCEPT_EULA=Y
    ports:
     - "5341:80"
    restart: unless-stopped
    volumes:
     - /Users/igrwijaya/Project/Infrastructure/DockerVolume/Seq/data:/data